version: '3.0'
services:

    api:
        build: ./api
        image: castiel-api
        container_name: castiel-api
        volumes:
            - ./api/src:/home/src
        expose:
            - 80
        ports:
            - "80:80"
        environment:
            - MONGOURL=mongodb://db.castiel_default:29200/default
